### ISSUE TITLE
[Umbrella][Feature] Introduce the basic workflow framework based on flinksql

### ISSUE THREAD

**Issue by leo65535** [apache/incubator-seatunnel#716]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The apache flink already contains rich connectors, and support sql grammar, batch and streaming source connectors, also 
contains many other excellent features, we can benefit from it. 

Several advantages:
1. more sources and sinks are supported, like kafka, hbase, greenplum.
2. workflows are isolated, each workflow is an independent yarn/k8s application.
3. lightweight ETL data process, like filter null.
4. support dimension table lookup in serveral cases.
5. support customized udfs.

To implement the new workflow, we need to use flink table api, it will help us handle the table schema, field datatype, 
and more high sql semantics, also it supports the integration of multiple data sources/sinks catalog.

Here is the flinksql workflow demo, 
```
CREATE TABLE kafka_source (
  customerId int,
  oStatus int,
  nStatus int
) with (
  'connector.type' = 'kafka',
  ...
  'connector.startup-mode' = 'earliest-offset',
  'format.type' = 'json'
);

CREATE TABLE fs_source (
  customerId int,
  oStatus int,
  nStatus int
) with (
  'connector.type' = 'filesystem',
  ...
  'path' = 'hdfs:///data/2021/06/01/xx.txt',
  'format.type' = 'json'
);

INSERT INTO fs_source
SELECT * FROM kafka_source
WHERE oStatus != 0;
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Task List
- [x] #727  
- [x] #757  
- [x] #801
- [x] #949

**Comment by leo65535** [comment]
cc @dailidong @garyelephant @RickyHuo, share your option when you are free.

**Comment by dailidong** [comment]
> INSERT INTO fs_source
> SELECT * FROM kafka_source
> WHERE oStatus != 0;

thanks for your detail design.

I think you can refer more open source projects, there is an open source project named DBT(https://www.getdbt.com) , maybe we can have a better solution

**Comment by leo65535** [comment]
Yeah, I plan to do the same thing that let workflow based on SQL.

![image](https://user-images.githubusercontent.com/95013770/143567934-ae5dd89d-ab86-4d0e-9a56-795870ff93b5.png)

**Comment by RickyHuo** [comment]
@leo65535 Thanks for your suggestion. In SeaTunnel, the Input source will register as a table, using SQL transform plugin could generate workflow based on SQL also. It seems as same as you said in some ways.

**Comment by leo65535** [comment]
hi @RickyHuo 

> In SeaTunnel, the Input source will register as a table, using SQL transform plugin could generate workflow based on SQL also

Yeah, you are right.

This point of this feature is introduce a new workflow template, show you the workflow demo.

**The origin workflow**
```
env {
  execution.parallelism = 1
}

source {
    FakeSourceStream {
      result_table_name = "fake"
      field_name = "name,age"
    }
}

transform {
    sql {
      sql = "select name,age from fake"
    }
}

sink {
  ConsoleSink {}
}
```

**The feature workflow**
```
CREATE TABLE fake_source (
  name string,
  age int
) with (
  'connector.type' = 'fakestream',
  'format.type' = 'json'
);

CREATE TABLE print_sink (
  name string,
  age int
) with (
  'connector.type' = 'print',
);

INSERT INTO fake_source
SELECT * FROM print_sink;
```
