### ISSUE TITLE
[Umbrella][flink] Upgrade flink version

### ISSUE THREAD

**Issue by leo65535** [apache/incubator-seatunnel#788]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In this stage, we should not move forward recklessly, it's better to choose flink-1.13.5 as the new version.
The develop api of flink1.13 has better compatibility, it contains old and new api, 
this will help us upgrade the version. And flink cdc[1] requires 1.13 version, it can't work with flink.1.14.

OK, here my detail steps to upgrade the version.

- Step1: Upgrade the flink to 1.13, ensure the original components are available as much as possible.

- Step2: In order to let sql and conf job share the same connectors, we need to add new job conf parser, and new core api

- Step3: Rich the connectors based on new core api.

[1] https://github.com/ververica/flink-cdc-connectors

[SeaTunnel Flink引擎版本升级.pptx](https://github.com/apache/incubator-seatunnel/files/7888549/SeaTunnel.Flink.pptx)

### Task list

- [x] #1083
- [x] #1252

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
For me, now may be the best time, but I'm not sure how many users of 1.9 have.

**Comment by leo65535** [comment]
Hi, @CalvinKirs, we can discuss it in mail list
https://lists.apache.org/thread/ml880ltvp1lbgtgcm9n5ynyw5kr6406y

**Comment by graphnj** [comment]
Is seatunnel 1.5.6 support flink?

I'm looking forward to use seatunnel with Flink1.14.

**Comment by leo65535** [comment]
> Is seatunnel 1.5.6 support flink?

No, `SeaTunnel` only support flink start from 2.x version.

**Comment by superguhua** [comment]
The functions of version 1.9 have not met most of the needs, and new branches can be opened for upgrades

**Comment by leo65535** [comment]
hi @superguhua @graphnj, here is the mail list, we can discuss it on it

https://lists.apache.org/thread/ml880ltvp1lbgtgcm9n5ynyw5kr6406y

**Comment by chaozwn** [comment]
Hi @leo65535 , i think we can support flink 1.13 or flink 1.14. we should use blink planer default. because in flink 1.14 the old planer has been deleted. and  seatunnel 2.x , we give up flink 1.9.

**Comment by 2000liux** [comment]
nice
