### ISSUE TITLE
[Feature][plugin-spark-source-jdbc] add jdbc connector settings in source config for easy used

### ISSUE THREAD

**Issue by Jack1007** [apache/incubator-seatunnel#844]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When I config plugin-spark-source-jdbc for one jdbc source,I found i can't set jdbc properties through its config file.I looked through the code and found  that jdbc source's config has no entrance to set properties for jdbc connector.The only way you can do this is through the URL like this eg:
  jdbc:mysql://localhost:3306/test?connectTimeout=10000&socketTimeout=10000
This url set connectTimeout and socketTimeout for the connector.
Then, I looked through spark's doc, I found this topic: https://spark.apache.org/docs/2.4.0/sql-data-sources-jdbc.html , in fact that spark  supports accepting the parameters of connector. It looks like this:
`val connectionProperties = new Properties()
connectionProperties.put("user", "username")
connectionProperties.put("password", "password")
val jdbcDF2 = spark.read
  .jdbc("jdbc:postgresql:dbserver", "schema.tablename", connectionProperties)
// Specifying the custom data types of the read schema
connectionProperties.put("customSchema", "id DECIMAL(38, 0), name STRING")
val jdbcDF3 = spark.read
  .jdbc("jdbc:postgresql:dbserver", "schema.tablename", connectionProperties)`

### Usage Scenario

Add a prefix for connector configtions, jdbc input config like this:
jdbc {
    driver = "com.mysql.jdbc.Driver"
    url = "jdbc:mysql://localhost:3306/info"
    table = "access"
    result_table_name = "access_log"
    user = "username"
    password = "password"
    jdbc.partitionColumn = "item_id"
    jdbc.numPartitions = "10"
    jdbc.lowerBound = 0
    jdbc.upperBound = 100
    conn.connectTimeout = 10000
    conn.socketTimeout = 10000
}

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
Anyone who wants to complete this function can leave a message~

**Comment by leo65535** [comment]
I checked the jdbc configuration in spark project. These two `connectTimeout` and `socketTimeout` are belong to `url` configuration item, we can not set them in other places.

> Add a prefix for connector configtions

`SeaTunnel` project already supports prefix, the prefix is `jdbc`

![image](https://user-images.githubusercontent.com/95013770/146910965-360b11b3-355b-46a4-b750-1d87305e40da.png)

**Comment by Jack1007** [comment]
> 

jdbc prefix is just for Spark Jdbc options, it's not for the connector.
Spark doc: https://spark.apache.org/docs/2.4.0/sql-data-sources-jdbc.html
![图片](https://user-images.githubusercontent.com/2090000/147024596-194935fc-eb9d-4051-ae32-30b39985a14e.png)

**Comment by dpchenxk** [comment]
> 

I want to do this

**Comment by ZhangchengHu0923** [comment]
@garyelephant @CalvinKirs @Jack1007 @leo65535 
The author of the issue seems to be write, and I'd like to handle this

**Comment by kyle-cx91** [comment]
# need attention for Jack1007
@Jack1007 Hi Jack,I have done some test, and it confirmed that the timeout config wouldn't work in config1, and config2 is the right way, u can do a test urself, by the way, my source database is Clickhouse
```
-- config 1 
jdbc:mysql://localhost:3306/test?connectTimeout=10000&socketTimeout=10000

-- config 2 
jdbc:mysql://localhost:3306/test?connect_timeout=10000&socket_timeout=10000
```

# Easy way to config
don't be surprise, this is exactly the easy way u like, I haven't changed any code, but review the code of spark-jdbc-source plugin,  guessing that connect_timeout/socket_timeout is no-special configuration, and our code has already handled them, I have done enough test to confirm the guess and  the configuration below.
@Jack1007 @garyelephant @CalvinKirs @leo65535 
```
source {
  jdbc {
    driver = "ru.yandex.clickhouse.ClickHouseDriver"
    url = "jdbc:clickhouse://192.168.1.111:8123/test"
    table = "st_source_date"
    result_table_name = "SOURCE_VIEW"
    user = "..."
    password = "..."

    jdbc.partitionColumn = "age"
    jdbc.numPartitions = "10"
    jdbc.lowerBound = 0
    jdbc.upperBound = 100

    jdbc.connect_timeout = 10000
    jdbc.socket_timeout = 10000
  }
}
```

# todo 
record the way to config connect_timeout/socket_timeout to the doc will be helpful, I'm handling this
@garyelephant @CalvinKirs @leo65535

**Comment by kyle-cx91** [comment]
@Jack1007 
# Steps to prove the timeout config works

## step1: timeout=10000

**note:** 192.168.1.111 is an ip address not exist, 

```
source {
  jdbc {
    driver = "ru.yandex.clickhouse.ClickHouseDriver"
    url = "jdbc:clickhouse://192.168.1.111:8123/test"
    table = "st_source_date"
    result_table_name = "SOURCE_VIEW"
    user = "..."
    password = "..."

    jdbc.connect_timeout = 10000
    jdbc.socket_timeout = 10000
  }
}
```

## Step2: run ur seatunnel pipline

it will take 10 secods to throw exception

## Step3: timeout=3000

**note:** 192.168.1.111 is an ip address not exist, 

```
source {
  jdbc {
    driver = "ru.yandex.clickhouse.ClickHouseDriver"
    url = "jdbc:clickhouse://192.168.1.111:8123/test"
    table = "st_source_date"
    result_table_name = "SOURCE_VIEW"
    user = "..."
    password = "..."

    jdbc.connect_timeout = 3000
    jdbc.socket_timeout = 3000
  }
}
```

## step4: run ur new seatunnel pipline

it will take 3 secods to throw exception

**Comment by wuchunfu** [comment]
@ZhangchengHu0923 We don't seem to be able to add `jdbc.connect_timeout` and `jdbc.socket_timeout` these two parameters to the `Data Source Option` . Please refer to the parameters supported by the `spark Data Source Option` : https://spark.apache.org/docs/latest/sql-data-sources-jdbc.html#data-source-option

**Comment by kyle-cx91** [comment]
> @ZhangchengHu0923 We don't seem to be able to add `jdbc.connect_timeout` and `jdbc.socket_timeout` these two parameters to the `Data Source Option` . Please refer to the parameters supported by the `spark Data Source Option` : https://spark.apache.org/docs/latest/sql-data-sources-jdbc.html#data-source-option

I have read the spark doc u post out, but what surprising me is that the configuration did works, I guess spark-jdbc haven't limit the params should be in the param list which lead some native JDBC params works. Welcome to verify according to the steps I provided earlier

@wuchunfu @CalvinKirs

**Comment by CalvinKirs** [comment]
cloused
