### ISSUE TITLE
[Umbrella] optimize the config module 

### ISSUE THREAD

**Issue by leo65535** [apache/incubator-seatunnel#903]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Describe the proposal

SeaTunnel use [config](https://github.com/lightbend/config) to parse app config file, and we did some changes

- Change path token separator from "." to "->"".
- Added parseObjectForseatunnel() to parse config objects in input, filter, output for seatunnel.
- Change package name to avoid implementation conflict when using this code with the official typesafe config used by Apache Flink.

But, as we know, it not appropriate that if we copy config sources to SeaTunnel project directly, so this issue aims to improve it.
This is a big changes, so I will split this issue into two sub issues to finish it.

### Task list

- [ ] #904
- [x] #753

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by leo65535** [comment]
Fixed at https://github.com/apache/incubator-seatunnel/pull/906, just one issue is enough.
